---
name: Trigger workflow for modified apps
on:
  push:

jobs:
  yamllint:
    name: Yamllint for github workflows
    runs-on: ubuntu-latest
    steps:
    - name: List all modified image paths
      run: echo 'linter'

  get-helm-paths:
    name: Get list of modified helm charts
    needs: yamllint
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.modified-helm-paths.outputs.all_modified_files }}
    steps:
    - name: Checkout this repository
      uses: actions/checkout@v4
    - name: Get modified helm paths
      id: modified-helm-paths
      uses: tj-actions/changed-files@v42
      with:
        dir_names: true
        dir_names_max_depth: '2'
        dir_names_exclude_current_dir: true
        files_ignore: '.github/**'
        files: '*/helm/'
        json: true
        escape_json: false
    - name: List all modified helm paths
      run: echo '${{ steps.modified-helm-paths.outputs.all_modified_files }}'

  get-images-paths:
    name: Get list of modified container image paths
    needs: yamllint
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.modified-images.outputs.all_modified_files }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Get modified images
      id: modified-images
      uses: tj-actions/changed-files@v42
      with:
        dir_names: true
        dir_names_max_depth: '3'
        dir_names_exclude_current_dir: true
        files_ignore: '.github/**'
        files: '*/images/'
        json: true
        escape_json: false
  
    - name: List all modified image paths
      run: |
        echo "test1" >> $GITHUB_OUTPUT
        echo '${{ steps.modified-images.outputs.all_modified_files }}'
        echo "GITHUB_OUTPUT=$GITHUB_OUTPUT"
        cat $GITHUB_OUTPUT
        ls -la $GITHUB_OUTPUT
        uname -a



  build-helm:
    if: ${{ needs.get-helm-paths.outputs.matrix != '[]' }}
    name: Build Helm
    needs: 
      - get-helm-paths
    strategy:
      max-parallel: 1
      matrix:
        chart: ${{ fromJSON(needs.get-helm-paths.outputs.matrix) }}
      fail-fast: false
    uses: ./.github/workflows/helm-build.yml
    secrets: inherit
    with:
      chart: ${{ matrix.chart }}

  build-container-images:
    if: ${{ needs.get-images-paths.outputs.matrix != '[]' }}
    name: Build container images
    needs: get-images-paths
    strategy:
      matrix:
        image: ${{ fromJSON(needs.get-images-paths.outputs.matrix) }}
      fail-fast: false
    uses: ./.github/workflows/container-image-build.yml
    secrets: inherit
    with:
      image: ${{ matrix.image }}
