---
name: Trigger workflow for modified apps
on:
  push:
  workflow_dispatch:
    inputs:
      rebuild_path:
        description: 'path to helm-chart or docker-image to rebuild'
        required: false
        type: string

jobs:
  yamllint:
    name: Yamllint for github workflows
    runs-on: ubuntu-latest
    steps:
    - name: List all modified image paths
      run: echo 'linter'

  get-images-paths:
    name: Get list of modified container image paths
    needs: yamllint
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.manual_path.outputs.all_modified_files }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Get modified images
      id: modified-images
      uses: tj-actions/changed-files@v42
      with:
        dir_names: true
        dir_names_max_depth: '3'
        dir_names_exclude_current_dir: true
        files_ignore: '.github/**'
        files: '*/images/'
        json: true
        escape_json: false
    - name: List all modified image paths
      run: echo '${{ steps.modified-images.outputs.all_modified_files }}'
    - name: add manual pathd
      id: manual_path
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ] && [ "${{inputs.rebuild_path}}" != "" ]; then 
          echo 'all_modified_files=["${{inputs.rebuild_path}}"]' >> "$GITHUB_OUTPUT"
        else 
          echo 'all_modified_files=${{ steps.modified-images.outputs.all_modified_files}}' >> "$GITHUB_OUTPUT"
        fi
    - name: list last modified image paths
      run:  echo '${{ steps.manual_path.outputs.all_modified_files }}'

  build-container-images:
    if: ${{ needs.get-images-paths.outputs.matrix != '[]' }}
    name: Build container images
    needs: get-images-paths
    strategy:
      matrix:
        image: ${{ fromJSON(needs.get-images-paths.outputs.matrix) }}
      fail-fast: false
    uses: ./.github/workflows/container-image-build.yml
    secrets: inherit
    with:
      image: ${{ matrix.image }}
