---
    name: Trigger workflow for modified apps
    on:
      workflow_dispatch:
        inputs:
          rebuild_path:
            description: 'path to helm-chart or docker-image to rebuild'
            required: true
            type: string
    jobs:
      yamllint:
        name: Yamllint for github workflows
        runs-on: ubuntu-latest
        steps:
        - name: List all modified image paths
          run: echo 'linter'
    
      get-images-paths:
        name: Get list of modified container image paths
        needs: yamllint
        runs-on: ubuntu-latest
        outputs:
          matrix: ${{ steps.modified-images.outputs.all_modified_files }}
        steps:
        - name: Get modified images
          id: modified-images
          run: echo "all_modified_files=${{inputs.rebuild_path}}" >> "$GITHUB_OUTPUT"
         
        - name: List all modified image paths
          run: echo '${{ steps.modified-images.outputs.all_modified_files }}'
    
    
      build-container-images:
        if: ${{ needs.get-images-paths.outputs.matrix != '[]' }}
        name: Build container images
        needs: get-images-paths
        strategy:
          matrix:
            image: ${{ fromJSON(needs.get-images-paths.outputs.matrix) }}
          fail-fast: false
        uses: ./.github/workflows/container-image-build.yml
        secrets: inherit
        with:
          image: ${{ matrix.image }}
    